"""Dump all NON-user (shipped/global) data to a portable SQL seed file.

Tables included: skins, global_providers, global_models, global_mcps,
global_skills, and skill_files for global skills. USER tables (users,
password_resets, user_configs, user_models, user_skills, user_mcps, sessions,
and user skill_files) are excluded.

Output: backend/app/db/seeds/global_seed.sql — portable across SQLite + Postgres
(TRUE/FALSE booleans, JSON as quoted string literals, ISO timestamps). Load into a
FRESH DB (after create_all / `alembic upgrade head`), before any user data exists.

Global-model API secrets (api_key / aws_*) are BLANKED by default — they are
environment secrets, not shareable seed data. Pass --with-secrets to include the
Fernet-encrypted blobs (only usable with the matching CREDENTIAL_ENCRYPTION_KEY).

Usage:  .venv/bin/python scripts/dump_global_seed_sql.py [--with-secrets]
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime

from sqlalchemy import select

from app.config import get_settings
from app.db import db_session, ensure_encryption_key, init_db, seed_all
from app.db.models import GlobalMcp, GlobalModel, GlobalProvider, GlobalSkill, SkillFile, Skin

OUT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "app", "db", "seeds", "global_seed.sql"))
SECRET_KEYS = ("api_key", "aws_secret_access_key", "aws_session_token", "aws_access_key_id")
WITH_SECRETS = "--with-secrets" in sys.argv[1:]


def sql_val(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):  # before int — bool is a subclass of int
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (dict, list)):
        s = json.dumps(v, ensure_ascii=False)
    elif isinstance(v, datetime):
        s = v.isoformat()
    else:
        s = str(v)
    return "'" + s.replace("'", "''") + "'"


def _blank_model_secrets(rec: dict) -> None:
    st = dict(rec.get("settings") or {})
    for k in SECRET_KEYS:
        if st.get(k):
            st[k] = ""
    rec["settings"] = st


async def _dump(ses, model, where=None, transform=None) -> list[str]:
    cols = [c.name for c in model.__table__.columns]
    stmt = select(model)
    if where is not None:
        stmt = stmt.where(where)
    rows = (await ses.scalars(stmt)).all()
    out = []
    for r in rows:
        rec = {c: getattr(r, c) for c in cols}
        if transform:
            transform(rec)
        vals = ", ".join(sql_val(rec[c]) for c in cols)
        out.append(f"INSERT INTO {model.__tablename__} ({', '.join(cols)}) VALUES ({vals});")
    return out


async def main() -> None:
    settings = get_settings()
    ensure_encryption_key(settings)
    await init_db()
    await seed_all(settings)  # make sure the global data is present to dump

    model_xform = None if WITH_SECRETS else _blank_model_secrets
    sections = [
        ("skins", Skin, None, None),
        ("global_providers", GlobalProvider, None, None),
        ("global_models", GlobalModel, None, model_xform),
        ("global_mcps", GlobalMcp, None, None),
        ("global_skills", GlobalSkill, None, None),
        ("skill_files (global skills only)", SkillFile, SkillFile.global_skill_id.isnot(None), None),
    ]
    lines = [
        "-- joyjoy — global (non-user) seed data. GENERATED by scripts/dump_global_seed_sql.py — do not hand-edit.",
        "-- Portable SQL (SQLite + Postgres). Load into a FRESH DB (after create_all / `alembic upgrade head`).",
        f"-- Global-model API keys: {'INCLUDED (Fernet-encrypted; needs matching CREDENTIAL_ENCRYPTION_KEY)' if WITH_SECRETS else 'BLANK (set via Settings -> Providers; env secrets are not seed data)'}.",
        "BEGIN;",
    ]
    async with db_session() as ses:
        for title, model, where, xform in sections:
            rows = await _dump(ses, model, where, xform)
            lines.append(f"\n-- {title}: {len(rows)} rows")
            lines.extend(rows)
    lines.append("\nCOMMIT;")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} KB, secrets={'included' if WITH_SECRETS else 'blank'})")


if __name__ == "__main__":
    asyncio.run(main())
